name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: pull docker
        uses: docker://amd64/rust
      - name: Rust Cache packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/cache
      - run: which cargo
      - name: Check out repository code
        uses: actions/checkout@v4
    #   - name: buildurlmock
    #     id: step1
    #     run: cargo build -r
      - name: builddata
        run: cp db.yaml urlmock
      - name: zip
        run: zip -r urlmock.zip keys static urlmock
      - name: tar
        run: tar -czvf urlmock.tar.gz keys static urlmock
      - name: out1
        id: out1
        run: echo "zip=${{ github.workspace }}/urlmock.zip" >> "$GITHUB_OUTPUT"
      - name: out2
        id: out2
        run: echo "tar=${{ github.workspace }}/urlmock.tar.gz" >> "$GITHUB_OUTPUT"
      - run: ls -alh
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
    outputs:
        output1: ${{ steps.out1.outputs.zip }}
        output2: ${{ steps.out2.outputs.tar }}
