name: Linuxæ‰“åŒ…
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: pull docker
        uses: docker://amd64/rust
      - name: Rust Cache packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/cache
      - run: which cargo
      - uses: actions/checkout@v4
      - name: buildurlmock
        id: step1
        run: cargo build -r
      - name: cpurlmock
        run: cp target/release/urlmock urlmock
      - name: zip
        run: zip -r urlmock.zip keys static urlmock
      - name: tar
        run: tar -czvf urlmock.tar.gz keys static urlmock
      - run: ls -alh
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Upload release assets
        id: action_gh_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Tran v0.2
          files: |
            urlmock.zip
            urlmock.tar.gz
          draft: true
          prerelease: false
